# Generated by Django 4.2 on 2023-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csvapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="csv_files/")),
            ],
        ),
        migrations.DeleteModel(
            name="CsvData",
        ),
    ]
